# Generated by Django 2.1.7 on 2019-02-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='invoice',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
