# Generated by Django 2.1.7 on 2019-02-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_auto_20190223_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
