# Generated by Django 2.1.7 on 2019-04-08 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_article_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
